# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 994bc329532c0e5f326a9aa4fa13e66d5ffaa4096bc01d1d054f9462a68c5f7a72a741321f7b8a6f8702b518fb94a2a3bdc174af42c269d476dc49b2941ba968

test:
  secret_key_base: 267393efe66cf2d1a2ebe2681eb4f2779e295dd533d05849489ba21c68347d129c735b727e839e8278af367931a1d20afc58e67ed738425fd1b407c8a70c589a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
